FROM ubuntu
RUN apt update && apt-get install build-essential -y && apt-get install gcc-multilib -y
COPY lab4_1.cpp lab4_2.cpp ./
RUN g++ lab4_1.cpp -o lab4_1 && g++ lab4_2.cpp -o lab4_2
CMD ./lab4_1
